import { messages } from "./i18n";

export type SchedulerWebviewStrings = Record<string, string>;

export function buildSchedulerWebviewStrings(
  uiLanguage: string,
): SchedulerWebviewStrings {
  const localize = (en: string, ja: string, de = en): string => {
    switch (uiLanguage) {
      case "ja":
        return ja;
      case "de":
        return de;
      default:
        return en;
    }
  };

  return {
    title: messages.webviewTitle(),
    tabTodoEditor: localize("Create Todo", "Todo を作成", "Todo erstellen"),
    tabTodoEditorCreate: localize("Create Todo", "Todo を作成", "Todo erstellen"),
    tabTodoEditorEdit: localize("Edit Todo", "Todo を編集", "Todo bearbeiten"),
    tabTaskEditor: localize("Create Task", "タスクを作成", "Task erstellen"),
    tabTaskEditorCreate: localize("Create Task", "タスクを作成", "Task erstellen"),
    tabTaskEditorEdit: localize("Edit Task", "タスクを編集", "Task bearbeiten"),
    tabUnsavedChanges: localize("Unsaved changes", "未保存の変更", "Ungespeicherte Änderungen"),
    tabCreate: messages.tabCreate(),
    tabEdit: messages.tabEdit(),
    tabList: messages.tabList(),
    tabHowTo: messages.tabHowTo(),
    tabHelpGlyph: "?",
    helpLanguageTitle: localize("Language", "言語", "Sprache"),
    helpLanguageBody: localize(
      "Change the cockpit language here. This updates the same workspace setting used in VS Code Settings.",
      "ここで Cockpit の言語を変更できます。VS Code の設定で使われる同じワークスペース設定を更新します。",
      "Hier können Sie die Sprache des Cockpit ändern. Dadurch wird dieselbe Workspace-Einstellung aktualisiert, die auch in den VS Code-Einstellungen verwendet wird.",
    ),
    helpLanguageLabel: localize("UI language", "UI言語", "UI-Sprache"),
    settingsLanguageTitle: localize("Language", "言語", "Sprache"),
    settingsLanguageBody: localize(
      "Change the cockpit language from Settings. This selector stays in sync with the one in How To.",
      "Settings から Cockpit の言語を変更できます。このセレクターは How To の言語設定と同期されます。",
      "Hier können Sie die Sprache des Cockpit in den Einstellungen ändern. Dieser Selektor bleibt mit dem im How To-Tab synchron.",
    ),
    settingsLanguageLabel: localize("UI language", "UI言語", "UI-Sprache"),
    helpLanguageAuto: localize("Auto-detect from VS Code", "VS Codeから自動検出", "Automatisch aus VS Code erkennen"),
    helpLanguageEnglish: "English",
    helpLanguageJapanese: "日本語",
    helpLanguageGerman: "Deutsch",
    helpIntroTitle: messages.helpIntroTitle(),
    helpIntroBody: messages.helpIntroBody(),
    helpTodoTitle: messages.helpTodoTitle(),
    helpTodoBody: messages.helpTodoBody(),
    helpSwitchTabSettingsBtn: messages.helpSwitchTabSettingsBtn(),
    helpSwitchTabTodoBtn: messages.helpSwitchTabTodoBtn(),
    helpSwitchTabCreateBtn: messages.helpSwitchTabCreateBtn(),
    helpSwitchTabListBtn: messages.helpSwitchTabListBtn(),
    helpSwitchTabJobsBtn: messages.helpSwitchTabJobsBtn(),
    helpSwitchTabResearchBtn: messages.helpSwitchTabResearchBtn(),
    helpAgentEcosystemTitle: localize(
      "11. Agent Ecosystem Integration",
      "11. エージェントエコシステム連携",
      "11. Agenten-Ökosystem-Integration",
    ),
    helpAgentEcosystemBody: localize(
      "Use the intro tutorial to learn the plugin first, then use plan integration to design repo-local skills, prompts, and agent roles around the Todo communication hub and scheduler MCP tools. With the right agent, MCP, and skill setup, this plugin can help build almost any company, because a company is ultimately a stream of the right discussions turned into the right work at the right time.",
      "まず Intro Tutorial でプラグインの全体像を理解し、その後 Plan Integration で Todo コミュニケーションハブと scheduler MCP ツールを中心に repo-local のスキル、プロンプト、エージェント役割を設計します。適切な agent、MCP、skill の構成がそろえば、このプラグインはほとんどあらゆる会社づくりを支えられます。会社とは結局、適切なタイミングで適切な議論を適切な実行へ変えていく流れだからです。",
      "Verwenden Sie zuerst das Intro Tutorial, um das Plugin kennenzulernen. Nutzen Sie danach Plan Integration, um repo-lokale Skills, Prompts und Agentenrollen rund um den Todo-Kommunikations-Hub und die Scheduler-MCP-Tools zu entwerfen. Mit dem richtigen Zusammenspiel aus agent, MCP und skills kann dieses Plugin helfen, nahezu jedes Unternehmen aufzubauen, denn ein Unternehmen ist letztlich eine Folge der richtigen Gespräche, die zur richtigen Zeit in die richtige Ausführung überführt werden.",
    ),
    helpIntroTutorialBtn: localize("Intro Tutorial", "Intro Tutorial", "Intro Tutorial"),
    helpPlanIntegrationBtn: localize("Plan Integration", "Plan Integration", "Integration planen"),
    helpCreateTitle: messages.helpCreateTitle(),
    helpCreateItemName: messages.helpCreateItemName(),
    helpCreateItemTemplates: messages.helpCreateItemTemplates(),
    helpCreateItemSkills: messages.helpCreateItemSkills(),
    helpCreateItemAgentModel: messages.helpCreateItemAgentModel(),
    helpCreateItemRunFirst: messages.helpCreateItemRunFirst(),
    helpListTitle: messages.helpListTitle(),
    helpListItemSections: messages.helpListItemSections(),
    helpListItemActions: messages.helpListItemActions(),
    helpListItemStartup: messages.helpListItemStartup(),
    helpStorageTitle: messages.helpStorageTitle(),
    helpStorageItemRepo: messages.helpStorageItemRepo(),
    helpStorageItemBackups: messages.helpStorageItemBackups(),
    helpStorageItemIsolation: messages.helpStorageItemIsolation(),
    helpStorageItemGlobal: messages.helpStorageItemGlobal(),
    helpOverdueTitle: messages.helpOverdueTitle(),
    helpOverdueItemReview: messages.helpOverdueItemReview(),
    helpOverdueItemRecurring: messages.helpOverdueItemRecurring(),
    helpOverdueItemOneTime: messages.helpOverdueItemOneTime(),
    helpSessionTitle: messages.helpSessionTitle(),
    helpSessionItemPerTask: messages.helpSessionItemPerTask(),
    helpSessionItemNewChat: messages.helpSessionItemNewChat(),
    helpSessionItemCareful: messages.helpSessionItemCareful(),
    helpSessionItemSeparate: messages.helpSessionItemSeparate(),
    helpMcpTitle: messages.helpMcpTitle(),
    helpMcpItemEmbedded: messages.helpMcpItemEmbedded(),
    helpMcpItemConfig: messages.helpMcpItemConfig(),
    helpMcpItemAutoConfig: messages.helpMcpItemAutoConfig(),
    helpMcpItemDanger: messages.helpMcpItemDanger(),
    helpMcpItemInspect: messages.helpMcpItemInspect(),
    helpMcpItemWrite: messages.helpMcpItemWrite(),
    helpMcpItemTools: messages.helpMcpItemTools(),
    helpJobsTitle: messages.helpJobsTitle(),
    tabBoard: localize("Todo Cockpit", "Todo Cockpit", "Todo Cockpit"),
    tabResearch: localize("Research", "Research", "Research"),
    helpJobsItemBoard: messages.helpJobsItemBoard(),
    helpJobsItemPause: messages.helpJobsItemPause(),
    helpJobsItemCompile: messages.helpJobsItemCompile(),
    helpJobsItemLabels: messages.helpJobsItemLabels(),
    helpJobsItemFolders: messages.helpJobsItemFolders(),
    helpJobsItemDelete: messages.helpJobsItemDelete(),
    helpResearchTitle: messages.helpResearchTitle(),
    helpResearchItemProfiles: messages.helpResearchItemProfiles(),
    helpResearchItemBounds: messages.helpResearchItemBounds(),
    helpResearchItemHistory: messages.helpResearchItemHistory(),
    tabTelegram: localize("Settings", "設定", "Einstellungen"),
    telegramTitle: localize("Telegram Notifications", "Telegram 通知", "Telegram-Benachrichtigungen"),
    telegramDescription: localize(
      "Configure a repo-local Stop hook that sends the last assistant reply to your Telegram bot.",
      "最後のアシスタント返信を Telegram bot へ送る、リポジトリローカルの Stop hook を設定します。",
      "Konfigurieren Sie einen repository-lokalen Stop hook, der die letzte Assistant-Antwort an Ihren Telegram bot sendet.",
    ),
    telegramEnable: localize("Enable Telegram Stop notification", "Telegram Stop 通知を有効化", "Telegram-Stop-Benachrichtigung aktivieren"),
    telegramBotToken: localize("Bot token", "Bot token", "Bot token"),
    telegramBotTokenPlaceholder: "123456:ABCDEF...",
    telegramBotTokenHelp: localize(
      "Stored only in .vscode/scheduler.private.json. Leave blank to keep the currently saved token.",
      ".vscode/scheduler.private.json にのみ保存されます。現在保存されている token を維持する場合は空欄のままにしてください。",
      "Wird nur in .vscode/scheduler.private.json gespeichert. Leer lassen, um das aktuell gespeicherte token beizubehalten.",
    ),
    telegramChatId: localize("Chat ID", "Chat ID", "Chat-ID"),
    telegramChatIdPlaceholder: "123456789 or -100...",
    telegramMessagePrefix: localize("Message prefix", "メッセージ接頭辞", "Nachrichtenpräfix"),
    telegramMessagePrefixPlaceholder: localize(
      "Optional short header shown above the last assistant reply.",
      "最後のアシスタント返信の上に表示される任意の短いヘッダーです。",
      "Optionaler kurzer Kopftext oberhalb der letzten Assistant-Antwort.",
    ),
    telegramSave: localize("Save Telegram Settings", "Telegram 設定を保存", "Telegram-Einstellungen speichern"),
    telegramTest: localize("Send Test Message", "テストメッセージを送信", "Testnachricht senden"),
    telegramSavedToken: localize("Bot token stored privately", "Bot token は非公開で保存済み", "Bot token privat gespeichert"),
    telegramMissingToken: localize("No bot token saved yet", "Bot token はまだ保存されていません", "Noch kein bot token gespeichert"),
    telegramHookReady: localize("Stop hook configured", "Stop hook は設定済み", "Stop hook konfiguriert"),
    telegramHookMissing: localize("Stop hook files not configured", "Stop hook ファイルは未設定", "Stop hook-Dateien nicht konfiguriert"),
    telegramUpdatedAt: localize("Last updated", "最終更新", "Zuletzt aktualisiert"),
    telegramWorkspaceNote: localize(
      "The hook files are generated under .github/hooks and read secrets from .vscode/scheduler.private.json.",
      "hook ファイルは .github/hooks 配下に生成され、秘密情報は .vscode/scheduler.private.json から読み取ります。",
      "Die hook-Dateien werden unter .github/hooks erzeugt und lesen Geheimnisse aus .vscode/scheduler.private.json.",
    ),
    telegramValidationChatId: localize("Telegram chat ID is required.", "Telegram chat ID が必要です。", "Eine Telegram chat ID ist erforderlich."),
    telegramValidationBotToken: localize("Telegram bot token is required.", "Telegram bot token が必要です。", "Ein Telegram bot token ist erforderlich."),
    telegramStatusSaved: localize(
      "Settings are repo-local. Save after changing chat ID, prefix, or token.",
      "設定はリポジトリローカルです。chat ID、prefix、token を変更した後は保存してください。",
      "Die Einstellungen sind repository-lokal. Speichern Sie nach Änderungen an chat ID, prefix oder token.",
    ),
    executionDefaultsTitle: localize("Execution Defaults", "実行デフォルト", "Ausführungsstandards"),
    executionDefaultsDescription: localize(
      "These workspace settings apply when a task, job step, research profile, or test run leaves agent or model empty.",
      "これらのワークスペース設定は、task、job step、research profile、test run で agent または model が空欄のときに適用されます。",
      "Diese Workspace-Einstellungen gelten, wenn ein task, job step, research profile oder test run agent oder model leer lässt.",
    ),
    executionDefaultsAgent: localize("Default agent", "デフォルト agent", "Standard-agent"),
    executionDefaultsModel: localize("Default model", "デフォルト model", "Standard-model"),
    executionDefaultsSave: localize("Save Defaults", "デフォルトを保存", "Defaults speichern"),
    executionDefaultsSaved: localize("Workspace default agent and model settings.", "ワークスペースのデフォルト agent / model 設定です。", "Workspace-Standardeinstellungen für agent und model."),
    settingsStorageTitle: localize("Workspace Storage", "ワークスペース保存先", "Workspace-Speicher"),
    settingsStorageBody: localize(
      "Choose the authoritative workspace backend. The setting is saved immediately, but reload the window after changing storage mode so every runtime surface rehydrates from the selected store.",
      "権威となるワークスペース保存先を選択します。設定はすぐ保存されますが、storage mode を変更した後は、すべての実行中コンポーネントが選択した保存先から再読込されるようウィンドウを再読み込みしてください。",
      "Wählen Sie das maßgebliche Workspace-Backend. Die Einstellung wird sofort gespeichert, aber nach einem Wechsel des storage mode sollte das Fenster neu geladen werden, damit alle Laufzeitkomponenten aus dem gewählten Speicher rehydrieren.",
    ),
    settingsStorageModeLabel: localize("Storage backend", "保存バックエンド", "Speicher-Backend"),
    settingsStorageModeJson: localize("JSON mirrors as primary store", "JSON ミラーを正本ストアにする", "JSON-Mirror als Primärspeicher verwenden"),
    settingsStorageModeSqlite: localize("SQLite as primary store", "SQLite を正本ストアにする", "SQLite als Primärspeicher verwenden"),
    settingsStorageMirrorLabel: localize("Keep JSON compatibility mirrors in sqlite mode", "sqlite mode でも JSON 互換ミラーを維持", "JSON-Kompatibilitäts-Mirror im sqlite mode beibehalten"),
    settingsDefaultFlagsTitle: localize("Built-in Cockpit flags", "組み込み Cockpit フラグ", "Integrierte Cockpit-Flags"),
    settingsDefaultFlagsBody: localize(
      "Turn built-in flags on or off for the default palette. Existing cards keep any flag they already use.",
      "組み込みフラグの既定パレット表示をオン/オフします。既存カードがすでに使っているフラグは保持されます。",
      "Schalten Sie integrierte Flags für die Standardpalette ein oder aus. Bereits auf Karten verwendete Flags bleiben erhalten.",
    ),
    settingsStorageSave: localize("Save Storage Settings", "保存設定を保存", "Speichereinstellungen speichern"),
    settingsStorageSaved: localize("Storage settings are repo-local. Reload after changing the backend mode.", "保存設定はリポジトリローカルです。バックエンド mode を変更した後は再読み込みしてください。", "Die Speichereinstellungen sind repository-lokal. Nach einem Wechsel des Backend-Modus neu laden."),
    settingsStorageVersionLabel: localize("Extension version", "拡張機能バージョン", "Erweiterungsversion"),
    settingsStorageMcpStatusLabel: localize("MCP support status", "MCP サポート状態", "MCP-Supportstatus"),
    settingsStorageMcpStatusConfigured: localize("Configured", "設定済み", "Konfiguriert"),
    settingsStorageMcpStatusMissing: localize("Missing", "未設定", "Fehlt"),
    settingsStorageMcpStatusStale: localize("Needs refresh", "更新が必要", "Muss aktualisiert werden"),
    settingsStorageMcpStatusInvalid: localize("Invalid", "無効", "Ungültig"),
    settingsStorageMcpStatusWorkspaceRequired: localize("Open a workspace to inspect", "確認するにはワークスペースを開いてください", "Öffnen Sie einen Workspace, um den Status zu prüfen"),
    settingsStorageLastMcpUpdateLabel: localize("Last MCP support update", "前回の MCP サポート更新", "Letzte MCP-Support-Aktualisierung"),
    settingsStorageLastSkillsUpdateLabel: localize("Last bundled skills update", "前回の bundled skills 更新", "Letzte Aktualisierung der bundled skills"),
    settingsStorageNeverUpdated: localize("Never", "なし", "Nie"),
    settingsStorageImportJsonToDb: localize("Import JSON Mirrors Into SQLite", "JSON ミラーを SQLite へ取り込む", "JSON-Mirror in SQLite importieren"),
    settingsStorageExportDbToJson: localize("Export SQLite Into JSON Mirrors", "SQLite を JSON ミラーへ書き出す", "SQLite in JSON-Mirror exportieren"),
    settingsStorageMaintenanceNote: localize(
      "Use these maintenance actions during rollout to force a JSON to SQLite reimport or to regenerate the compatibility JSON mirrors from the current SQLite runtime state.",
      "ロールアウト中は、これらの保守アクションで JSON から SQLite への再取込や、現在の SQLite ランタイム状態から互換 JSON ミラーの再生成を強制できます。",
      "Verwenden Sie diese Wartungsaktionen während des Rollouts, um einen erneuten Import von JSON nach SQLite zu erzwingen oder die Kompatibilitäts-Mirror aus dem aktuellen SQLite-Laufzeitstand neu zu erzeugen.",
    ),
    settingsLoggingTitle: localize("Diagnostics Logging", "診断ログ", "Diagnose-Logging"),
    settingsLoggingBody: localize(
      "Write host and targeted webview diagnostics into a repo-local log folder while debugging installed UI issues.",
      "インストール済み UI の不具合を調査している間、host と対象 Webview の診断情報をリポジトリローカルのログフォルダーへ書き込みます。",
      "Schreibt Host- und gezielte Webview-Diagnosen in einen repository-lokalen Log-Ordner, solange installierte UI-Probleme untersucht werden.",
    ),
    settingsLoggingLevelLabel: localize("Log level", "ログレベル", "Log-Level"),
    settingsLoggingLevelNone: localize("Off", "オフ", "Aus"),
    settingsLoggingLevelError: localize("Errors only", "エラーのみ", "Nur Fehler"),
    settingsLoggingLevelInfo: localize("Info", "Info", "Info"),
    settingsLoggingLevelDebug: localize("Detailed debug", "詳細デバッグ", "Detailliertes Debug"),
    settingsLoggingDirectoryLabel: localize("Log folder", "ログフォルダー", "Log-Ordner"),
    settingsLoggingOpenFolder: localize("Open Log Folder", "ログフォルダーを開く", "Log-Ordner öffnen"),
    settingsLoggingDirectoryHint: localize(
      "Detailed webview logging is only emitted when log level is set to Detailed debug.",
      "詳細な Webview ログは、ログレベルが「詳細デバッグ」のときだけ出力されます。",
      "Detaillierte Webview-Logs werden nur ausgegeben, wenn das Log-Level auf Detailliertes Debug gesetzt ist.",
    ),
    boardTitle: localize("Todo Cockpit", "Todo Cockpit", "Todo Cockpit"),
    boardDescription: localize(
      "Local-only planning and approval workspace. Todos stay distinct from scheduled tasks. Recurring tasks keep one persistent history card in a dedicated hidden section, while one-time tasks normally stay linked to their originating todo.",
      "ローカル専用の計画・承認ワークスペースです。Todo は scheduled tasks と分離されたまま保持されます。recurring tasks は専用の非表示セクションに永続的な履歴カードを持ち、one-time tasks は通常その元になった todo にリンクされたままです。",
      "Ein lokaler Bereich für Planung und Freigabe. Todos bleiben von scheduled tasks getrennt. Wiederkehrende tasks behalten eine dauerhafte Verlaufskarte in einem eigenen ausgeblendeten Bereich, während one-time tasks normalerweise mit ihrem ursprünglichen Todo verknüpft bleiben.",
    ),
    boardEmpty: localize("No todos yet. Create one here, or reveal Recurring Tasks to inspect recurring-task history cards.", "まだ Todo はありません。ここで作成するか、Recurring Tasks を表示して recurring-task の履歴カードを確認してください。", "Noch keine Todos. Erstellen Sie hier eins oder blenden Sie Recurring Tasks ein, um Verlaufskarten wiederkehrender tasks zu sehen."),
    boardSections: localize("Sections", "セクション", "Bereiche"),
    boardCards: localize("Cards", "カード", "Karten"),
    boardComments: localize("Comments", "コメント", "Kommentare"),
    boardPrivacyNote: localize(
      "Todo Cockpit state is kept only in .vscode/scheduler.private.json so user-system planning stays local to this workspace.",
      "Todo Cockpit の状態は .vscode/scheduler.private.json にのみ保存され、ユーザーとシステムの計画情報はこのワークスペースにローカルなまま保持されます。",
      "Der Zustand des Todo Cockpit wird nur in .vscode/scheduler.private.json gespeichert, damit die Planung zwischen Benutzer und System lokal in diesem Workspace bleibt.",
    ),
    boardToolbarNew: localize("New Todo", "新しい Todo", "Neues Todo"),
    boardToolbarClear: localize("Clear Selection", "選択をクリア", "Auswahl aufheben"),
    boardToolbarClearFilters: localize("Clear Filters", "フィルターをクリア", "Filter löschen"),
    boardFiltersTitle: localize("Filters", "フィルター", "Filter"),
    boardShowFilters: localize("Show Filters", "フィルターを表示", "Filter anzeigen"),
    boardHideFilters: localize("Hide Filters", "フィルターを隠す", "Filter ausblenden"),
    boardSearchLabel: localize("Search", "検索", "Suche"),
    boardSearchPlaceholder: localize("Search title, description, labels, comments", "タイトル、説明、ラベル、コメントを検索", "Titel, Beschreibung, Labels und Kommentare durchsuchen"),
    boardSortLabel: localize("Sort", "並び替え", "Sortieren"),
    boardViewLabel: localize("View", "表示", "Ansicht"),
    boardSectionFilterLabel: localize("Section", "セクション", "Bereich"),
    boardLabelFilterLabel: localize("Label", "ラベル", "Label"),
    boardFlagFilterLabel: localize("Flag", "Flag", "Flag"),
    boardPriorityFilterLabel: localize("Priority", "優先度", "Priorität"),
    boardStatusFilterLabel: localize("Status", "ステータス", "Status"),
    boardArchiveOutcomeFilterLabel: localize("Archive outcome", "アーカイブ結果", "Archiv-Ergebnis"),
    boardAllFlags: localize("All flags", "すべての Flags", "Alle Flags"),
    boardShowArchived: localize("Show archived", "アーカイブを表示", "Archivierte anzeigen"),
    boardShowRecurringTasks: localize("Show recurring tasks", "Recurring Tasks を表示", "Wiederkehrende Tasks anzeigen"),
    boardHideCardDetails: localize("Hide card details", "カード詳細を隠す", "Kartendetails ausblenden"),
    boardAllSections: localize("All sections", "すべてのセクション", "Alle Bereiche"),
    boardAllLabels: localize("All labels", "すべてのラベル", "Alle Labels"),
    boardAllPriorities: localize("All priorities", "すべての優先度", "Alle Prioritäten"),
    boardAllStatuses: localize("All statuses", "すべてのステータス", "Alle Status"),
    boardAllArchiveOutcomes: localize("All outcomes", "すべての結果", "Alle Ergebnisse"),
    boardSortManual: localize("Manual order", "手動順", "Manuelle Reihenfolge"),
    boardSortDueAt: localize("Due date", "期限", "Fälligkeitsdatum"),
    boardSortPriority: localize("Priority", "優先度", "Priorität"),
    boardSortUpdatedAt: localize("Last updated", "最終更新", "Zuletzt aktualisiert"),
    boardSortCreatedAt: localize("Created date", "作成日", "Erstellt am"),
    boardSortAsc: localize("Ascending", "昇順", "Aufsteigend"),
    boardSortDesc: localize("Descending", "降順", "Absteigend"),
    boardViewBoard: localize("Board", "ボード", "Board"),
    boardViewList: localize("List", "リスト", "Liste"),
    boardListEmptySection: localize("No todos in this section.", "このセクションには Todo がありません。", "Keine Todos in diesem Bereich."),
    boardListRowEdited: localize("Updated", "更新", "Aktualisiert"),
    boardDetailTitleCreate: localize("Create Todo", "Todo を作成", "Todo erstellen"),
    boardDetailTitleEdit: localize("Edit Todo", "Todo を編集", "Todo bearbeiten"),
    boardDetailModeCreate: localize("Fill the form to create a new Todo Cockpit item.", "フォームに入力して新しい Todo Cockpit 項目を作成します。", "Füllen Sie das Formular aus, um ein neues Todo Cockpit-Element zu erstellen."),
    boardDetailModeEdit: localize("Update fields, manage labels, and move the item through approval, completion, or rejection.", "フィールドを更新し、ラベルを管理し、承認・完了・却下の流れで項目を進めます。", "Aktualisieren Sie Felder, verwalten Sie Labels und bewegen Sie das Element durch Freigabe, Abschluss oder Ablehnung."),
    boardFieldTitle: localize("Title", "タイトル", "Titel"),
    boardFieldDescription: localize("Description", "説明", "Beschreibung"),
    boardFieldDueAt: localize("Due date", "期限", "Fälligkeitsdatum"),
    boardFieldSection: localize("Section", "セクション", "Bereich"),
    boardFieldPriority: localize("Priority", "優先度", "Priorität"),
    boardFieldLabels: localize("Labels", "ラベル", "Labels"),
    boardFieldFlags: localize("Flag (agent state)", "Flag（agent state）", "Flag (agent state)"),
    boardFlagAdd: localize("Add Flag", "Flag を追加", "Flag hinzufügen"),
    boardFlagClear: localize("Clear", "クリア", "Leeren"),
    boardFlagClearTitle: localize("Clear flag", "Flag をクリア", "Flag entfernen"),
    boardFlagNone: localize("No flag set.", "Flag は設定されていません。", "Kein Flag gesetzt."),
    boardFlagCatalogHint: localize("Click a flag to set it. Only one flag at a time.", "Flag をクリックして設定します。一度に 1 つだけ設定できます。", "Klicken Sie auf ein Flag, um es zu setzen. Es kann jeweils nur ein Flag aktiv sein."),
    boardFlagCatalogSelectTitle: localize("Set as flag", "Flag として設定", "Als Flag setzen"),
    boardFlagCatalogEditTitle: localize("Edit flag", "Flag を編集", "Flag bearbeiten"),
    boardFlagCatalogDeleteTitle: localize("Delete flag", "Flag を削除", "Flag löschen"),
    boardFlagCatalogDeleteConfirm: localize('Delete flag "{name}"?', 'Flag「{name}」を削除しますか？', 'Flag "{name}" löschen?'),
    boardFlagCatalogLockedTitle: localize("Built-in flag", "組み込みフラグ", "Integriertes Flag"),
    boardFlagPresetGo: localize("Ready", "準備完了", "Bereit"),
    boardFlagPresetRejected: localize("Rejected", "却下", "Abgelehnt"),
    boardFlagPresetNeedsBotReview: localize("Needs bot review", "Bot レビュー待ち", "Bot-Prüfung nötig"),
    boardFlagPresetNeedsUserReview: localize("Needs user review", "ユーザーレビュー待ち", "Benutzerprüfung nötig"),
    boardFlagPresetNew: localize("New", "新規", "Neu"),
    boardFieldLinkedTask: localize("Linked task", "リンクされた task", "Verknüpfte Aufgabe"),
    boardLinkedTaskNone: localize("No linked task", "リンクされた task はありません", "Kein verknüpfter task"),
    boardSaveCreate: localize("Create Todo", "Todo を作成", "Todo erstellen"),
    boardSaveUpdate: localize("Save Todo", "Todo を保存", "Todo speichern"),
    boardAddComment: localize("Add Comment", "コメントを追加", "Kommentar hinzufügen"),
    boardCommentsEyebrow: localize("Conversation thread", "会話スレッド", "Konversationsthread"),
    boardCommentsCreateIntro: localize("Start the thread early so context, approvals, and decisions do not get buried in the description.", "説明欄に埋もれないよう、コンテキストや承認、判断を最初のスレッドとして残します。", "Starten Sie den Thread früh, damit Kontext, Freigaben und Entscheidungen nicht in der Beschreibung untergehen."),
    boardCommentsEditIntro: localize("Keep approvals, decisions, and handoff context in the thread while the main description stays stable.", "説明を安定させたまま、承認・判断・引き継ぎの文脈はスレッド側に残します。", "Bewahren Sie Freigaben, Entscheidungen und Übergabekontext im Thread auf, während die Hauptbeschreibung stabil bleibt."),
    boardCommentModeCreate: localize("Kickoff note", "開始メモ", "Auftaktnotiz"),
    boardCommentModeEdit: localize("Live thread", "進行中スレッド", "Aktiver Thread"),
    boardCommentBadgeDraft: localize("Draft", "ドラフト", "Entwurf"),
    boardCommentBadgePreview: localize("Preview", "プレビュー", "Vorschau"),
    boardCommentComposerCreateTitle: localize("Write the kickoff comment", "開始コメントを書く", "Auftaktkommentar schreiben"),
    boardCommentComposerEditTitle: localize("Add to the thread", "スレッドへ追記", "Zum Thread hinzufügen"),
    boardCommentCreateHint: localize("Optional, but recommended: add the first human note now so the todo starts with useful context.", "任意ですが推奨です。最初の人間メモを今入れておくと、Todo が有用な文脈付きで始まります。", "Optional, aber empfohlen: Fügen Sie jetzt die erste menschliche Notiz hinzu, damit das Todo mit nützlichem Kontext startet."),
    boardCommentCreateReady: localize("This draft will be saved as the first human comment when you create the todo.", "このドラフトは Todo 作成時に最初の人間コメントとして保存されます。", "Dieser Entwurf wird beim Erstellen des Todos als erster menschlicher Kommentar gespeichert."),
    boardCommentEditHint: localize("Add a focused update without rewriting the full description.", "説明全体を書き直さずに、必要な更新だけを追加します。", "Fügen Sie ein gezieltes Update hinzu, ohne die gesamte Beschreibung umzuschreiben."),
    boardCommentReadyToAdd: localize("Ready to append to the live thread.", "進行中スレッドへ追加する準備ができています。", "Bereit, an den aktiven Thread angehängt zu werden."),
    boardCommentCreatePlaceholder: localize("Capture the first decision, approval note, or handoff context for this todo...", "この Todo の最初の判断、承認メモ、または引き継ぎコンテキストを記録します…", "Erfassen Sie die erste Entscheidung, Freigabenotiz oder den Übergabekontext für dieses Todo..."),
    boardCommentThreadTitle: localize("Thread preview", "スレッドプレビュー", "Thread-Vorschau"),
    boardCommentThreadCreateNote: localize("Preview of the kickoff note that will be saved on create.", "作成時に保存される開始メモのプレビューです。", "Vorschau der Auftaktnotiz, die beim Erstellen gespeichert wird."),
    boardCommentThreadCreateEmpty: localize("Start typing to preview the kickoff comment.", "入力を始めると開始コメントのプレビューが表示されます。", "Beginnen Sie zu tippen, um den Auftaktkommentar in der Vorschau zu sehen."),
    boardCommentThreadEditNote: localize("Open any card to read the full comment or remove a thread entry.", "カードを開くとコメント全文を読んだり、スレッド項目を削除したりできます。", "Öffnen Sie eine Karte, um den vollständigen Kommentar zu lesen oder einen Thread-Eintrag zu entfernen."),
    boardCommentPreviewPending: localize("Saved on create", "作成時に保存", "Wird beim Erstellen gespeichert"),
    boardCreateTask: localize("Create Task Draft", "Task Draft を作成", "Task Draft erstellen"),
    boardApproveTodo: localize("Approve", "承認", "Freigeben"),
    boardCompleteTodo: localize("Complete & Archive", "完了してアーカイブ", "Abschließen und archivieren"),
    boardFinalizeTodo: localize("Final Accept", "最終承認", "Final akzeptieren"),
    boardDeclineTodo: localize("Decline", "却下", "Ablehnen"),
    boardRestoreTodo: localize("Restore", "戻す", "Wiederherstellen"),
    boardDeleteTodo: localize("Delete Todo", "Todo を削除", "Todo löschen"),
    boardDeleteTodoShort: localize("Delete", "削除", "Löschen"),
    boardEditTodoShort: localize("Edit", "編集", "Bearbeiten"),
    boardDeleteTodoHelp: localize("Reject and archive this todo.", "この Todo を却下してアーカイブします。", "Dieses Todo ablehnen und archivieren."),
    boardDeleteTodoTitle: localize("Delete Todo", "Todo を削除", "Todo löschen"),
    boardDeleteTodoPrompt: localize("Choose whether this todo should be rejected into the archive or removed permanently.", "この Todo を却下してアーカイブするか、完全に削除するかを選択してください。", "Wählen Sie, ob dieses Todo abgelehnt und archiviert oder dauerhaft gelöscht werden soll."),
    boardDeleteTodoPermanentPrompt: localize("Delete this archived todo permanently? This cannot be undone.", "このアーカイブ済み Todo を完全に削除しますか？この操作は元に戻せません。", "Dieses archivierte Todo dauerhaft löschen? Diese Aktion kann nicht rückgängig gemacht werden."),
    boardDeleteTodoReject: localize("Archive as Rejected", "却下としてアーカイブ", "Als abgelehnt archivieren"),
    boardDeleteTodoPermanent: localize("Delete Permanently", "完全に削除", "Dauerhaft löschen"),
    boardDeleteTodoCancel: localize("Cancel", "キャンセル", "Abbrechen"),
    boardFinalizeTodoYes: localize("Yes", "はい", "Ja"),
    boardFinalizeTodoNo: localize("No", "いいえ", "Nein"),
    boardFinalizePrompt: localize("Archive this todo as completed successfully?", "この Todo を正常完了としてアーカイブしますか？", "Dieses Todo als erfolgreich abgeschlossen archivieren?"),
    boardDescriptionLabel: localize("Description", "説明", "Beschreibung"),
    boardConfirmAction: localize("Confirm", "確認", "Bestätigen"),
    boardCancelAction: localize("Cancel", "キャンセル", "Abbrechen"),
    boardConfirmApproveHint: localize("Click Confirm to continue, or Cancel to keep the todo unchanged.", "続行するには「確認」、変更しない場合は「キャンセル」をクリックしてください。", "Klicken Sie auf Bestätigen, um fortzufahren, oder auf Abbrechen, um das Todo unverändert zu lassen."),
    boardReadOnlyArchived: localize("Archived items are read-only in the editor. Use Restore on the board to reopen them.", "アーカイブ済み項目はエディターでは読み取り専用です。ボード上の「戻す」を使って再開してください。", "Archivierte Elemente sind im Editor schreibgeschützt. Verwenden Sie im Board Wiederherstellen, um sie erneut zu öffnen."),
    boardReadyForTask: localize("Approved items can become scheduled task drafts or be final accepted.", "承認済み項目は scheduled task drafts にするか、最終承認できます。", "Freigegebene Elemente können zu scheduled task drafts werden oder final akzeptiert werden."),
    boardCommentsTitle: localize("Comments", "コメント", "Kommentare"),
    boardCommentsEmpty: localize("No comments yet.", "まだコメントはありません。", "Noch keine Kommentare."),
    boardCommentOpenFull: localize("Open full comment", "コメント全体を開く", "Vollständigen Kommentar öffnen"),
    boardCommentModalTitle: localize("Comment Detail", "コメント詳細", "Kommentardetails"),
    boardCommentPlaceholder: localize("Add a comment with context, provenance, or approval notes...", "コンテキスト、provenance、承認メモを含むコメントを追加...", "Kommentar mit Kontext, provenance oder Freigabenotizen hinzufügen..."),
    boardCommentSourceHumanForm: localize("Human form", "Human form", "Menschliches Formular"),
    boardCommentSourceBotMcp: localize("Bot MCP", "Bot MCP", "Bot MCP"),
    boardCommentSourceBotManual: localize("Bot manual", "Bot manual", "Bot manuell"),
    boardCommentSourceSystemEvent: localize("System event", "System event", "Systemereignis"),
    boardUploadFiles: localize("Upload Files", "ファイルをアップロード", "Dateien hochladen"),
    boardUploadFilesHint: localize("Copies files into .vscode/cockpit-input-uploads and inserts the local paths into the description.", ".vscode/cockpit-input-uploads にファイルをコピーし、説明欄にローカルパスを挿入します。", "Kopiert Dateien nach .vscode/cockpit-input-uploads und fügt die lokalen Pfade in die Beschreibung ein."),
    boardUploadFilesSuccess: localize("Files copied into the workspace input folder and added to the description.", "ファイルをワークスペース入力フォルダーにコピーし、説明欄へ追加しました。", "Dateien wurden in den Workspace-Eingabeordner kopiert und der Beschreibung hinzugefügt."),
    boardUploadFilesEmpty: localize("No files selected.", "ファイルが選択されていません。", "Keine Dateien ausgewählt."),
    boardUploadFilesError: localize("File upload failed.", "ファイルのアップロードに失敗しました。", "Datei-Upload fehlgeschlagen."),
    boardTaskDraftNote: localize("Scheduled tasks are downstream execution artifacts. Creating a task draft here does not replace the todo.", "Scheduled tasks は下流の実行成果物です。ここで task draft を作成しても todo 自体は置き換わりません。", "Scheduled tasks sind nachgelagerte Ausführungsartefakte. Wenn Sie hier einen task draft erstellen, ersetzt das nicht das Todo selbst."),
    boardDueLabel: localize("Due", "期限", "Fällig"),
    boardTaskMissing: localize("Linked task not found in Task List.", "リンクされた task は Task List に見つかりません。", "Verknüpfter task wurde in der Task List nicht gefunden."),
    boardTaskLinked: localize("Linked task", "リンクされた task", "Verknüpfter task"),
    boardStatusLabel: localize("Status", "ステータス", "Status"),
    boardStatusActive: localize("Active", "アクティブ", "Aktiv"),
    boardStatusReady: localize("Ready", "準備完了", "Bereit"),
    boardStatusCompleted: localize("Completed", "完了", "Abgeschlossen"),
    boardStatusRejected: localize("Rejected", "却下", "Abgelehnt"),
    boardArchiveCompletedSuccessfully: localize("Completed successfully", "正常に完了", "Erfolgreich abgeschlossen"),
    boardArchiveRejected: localize("Rejected", "却下", "Abgelehnt"),
    boardLatestComment: localize("Latest comment", "最新コメント", "Neuester Kommentar"),
    boardLabelInputPlaceholder: localize("Type a label and press Enter", "ラベルを入力して Enter を押してください", "Label eingeben und Enter drücken"),
    boardLabelAdd: localize("Add", "追加", "Hinzufügen"),
    boardLabelCatalogAddTitle: localize("Add to todo", "Todo に追加", "Zum Todo hinzufügen"),
    boardLabelCatalogEditTitle: localize("Edit label", "Label を編集", "Label bearbeiten"),
    boardLabelCatalogDeleteTitle: localize("Delete label", "Label を削除", "Label löschen"),
    boardLabelCatalogDeleteConfirm: localize('Delete label "{name}"?', 'Label「{name}」を削除しますか？', 'Label "{name}" löschen?'),
    boardLabelSaveColor: localize("Save Color", "色を保存", "Farbe speichern"),
    boardLabelHint: localize("Click a chip to target its shared color. Press Enter to add more labels.", "チップをクリックすると共有色を対象にできます。Enter でラベルを追加します。", "Klicken Sie auf ein Chip, um seine gemeinsame Farbe auszuwählen. Mit Enter fügen Sie weitere Labels hinzu."),
    boardNoLinkedTask: localize("No linked task yet", "まだリンクされた task はありません", "Noch kein verknüpfter task"),
    boardLinkedTaskShort: localize("Linked", "Linked", "Verknüpft"),
    boardDescriptionPreviewEmpty: localize("No description yet.", "まだ説明はありません。", "Noch keine Beschreibung."),
    boardSectionCollapse: localize("Collapse section", "セクションを折りたたむ", "Bereich einklappen"),
    boardSectionExpand: localize("Expand section", "セクションを展開", "Bereich ausklappen"),
    boardSectionUntitled: localize("Section", "セクション", "Bereich"),
    boardSectionRename: localize("Rename section", "セクション名を変更", "Bereich umbenennen"),
    boardSectionDelete: localize("Delete section", "セクションを削除", "Bereich löschen"),
    boardDeleteConfirm: localize("Delete?", "削除しますか？", "Löschen?"),
    boardCardUntitled: localize("Untitled", "無題", "Ohne Titel"),
    boardEditTodo: localize("Open Editor", "エディターを開く", "Editor öffnen"),
    boardBackToCockpit: localize("Back to Cockpit", "Cockpit に戻る", "Zurück zum Cockpit"),
    boardPriorityNone: localize("None", "なし", "Keine"),
    boardPriorityLow: localize("Low", "低", "Niedrig"),
    boardPriorityMedium: localize("Medium", "中", "Mittel"),
    boardPriorityHigh: localize("High", "高", "Hoch"),
    boardPriorityUrgent: localize("Urgent", "緊急", "Dringend"),
    boardDropHint: localize("Drag between columns to reorder or move todos.", "列の間でドラッグして todo を並べ替えたり移動したりできます。", "Zwischen Spalten ziehen, um Todos neu anzuordnen oder zu verschieben."),
    boardAddSection: localize("+ Add Section", "+ セクションを追加", "+ Bereich hinzufügen"),
    boardSectionNamePlaceholder: localize("Section name...", "セクション名...", "Bereichsname..."),
    commonAdd: localize("Add", "追加", "Hinzufügen"),
    commonCancel: localize("Cancel", "キャンセル", "Abbrechen"),
    helpTipsTitle: messages.helpTipsTitle(),
    helpTipsItem1: messages.helpTipsItem1(),
    helpTipsItem2: messages.helpTipsItem2(),
    helpTipsItem3: messages.helpTipsItem3(),
    labelTaskName: messages.labelTaskName(),
    tabJobsEditor: localize("Create Job", "Job を作成", "Job erstellen"),
    tabJobsEditorCreate: localize("Create Job", "Job を作成", "Job erstellen"),
    tabJobsEditorEdit: localize("Edit Job", "Job を編集", "Job bearbeiten"),
    tabJobs: localize("Jobs", "Jobs", "Jobs"),
    labelTaskLabels: localize("Labels", "ラベル", "Labels"),
    placeholderTaskLabels: "marketing, finance, weekly",
    labelSkills: messages.labelSkills(),
    placeholderSelectSkill: messages.placeholderSelectSkill(),
    actionInsertSkill: messages.actionInsertSkill(),
    skillInsertNote: messages.skillInsertNote(),
    skillSentenceTemplate: messages.skillSentenceTemplate("{skill}"),
    actionSetupMcp: messages.mcpSetupAction(),
    actionSyncBundledSkills: localize("Sync Bundled Skills", "同梱スキルを同期", "Gebündelte Skills synchronisieren"),
    settingsMaintenanceTitle: localize("Workspace Maintenance", "ワークスペース保守", "Workspace-Wartung"),
    settingsMaintenanceBody: localize(
      "Repair repo-local support files after plugin updates. Use this when a workspace was opened before new bundled skills were added.",
      "プラグイン更新後に repo-local の補助ファイルを補修します。新しい同梱スキルが追加される前からワークスペースを開いていた場合に使います。",
      "Repariert repo-lokale Unterstützungsdateien nach Plugin-Updates. Verwenden Sie dies, wenn ein Workspace bereits geöffnet war, bevor neue gebündelte Skills hinzugefügt wurden.",
    ),
    labelFilterByLabel: localize("Filter by label", "ラベルでフィルター", "Nach Label filtern"),
    labelAllLabels: localize("All labels", "すべてのラベル", "Alle Labels"),
    jobsTitle: localize("Jobs", "Jobs", "Jobs"),
    jobsFoldersTitle: localize("Folders", "フォルダー", "Ordner"),
    jobsRootFolder: localize("All jobs", "すべての Jobs", "Alle Jobs"),
    jobsCurrentFolderLabel: localize("Current folder", "現在のフォルダー", "Aktueller Ordner"),
    jobsCurrentFolderBadge: localize("Current", "現在", "Aktuell"),
    jobsArchiveFolder: localize("Bundled Jobs", "Bundled Jobs", "Gebündelte Jobs"),
    jobsCreateFolder: localize("New Folder", "新しいフォルダー", "Neuer Ordner"),
    jobsCreateJob: localize("New Job", "新しい Job", "Neuer Job"),
    jobsOpenEditor: localize("Open Editor", "エディターを開く", "Editor öffnen"),
    jobsBackToJobs: localize("Back to Jobs", "Jobs に戻る", "Zurück zu Jobs"),
    jobsOverviewTitle: localize("Jobs Overview", "Jobs 概要", "Jobs-Überblick"),
    jobsOverviewNote: localize("Keep folders and job selection here, then open the dedicated editor tab when you want to change workflow details.", "ここではフォルダーと job 選択を管理し、ワークフロー詳細を変更したいときに専用エディタータブを開きます。", "Verwalten Sie hier Ordner und Job-Auswahl und öffnen Sie dann den dedizierten Editor-Tab, wenn Sie Workflow-Details ändern möchten."),
    jobsEditorDetailsTitle: localize("Job details", "Job の詳細", "Job-Details"),
    jobsEditorDetailsNote: localize("Name the job, place it in a folder, and toggle whether it is active.", "Job に名前を付け、フォルダーに配置し、アクティブにするかどうかを切り替えます。", "Benennen Sie den Job, ordnen Sie ihn einem Ordner zu und schalten Sie um, ob er aktiv ist。"),
    jobsEditorScheduleNote: localize("Choose a preset, edit the cron expression, or use the friendly builder.", "プリセットを選択し、cron 式を編集するか、friendly builder を使います。", "Wählen Sie ein Preset, bearbeiten Sie den Cron-Ausdruck oder verwenden Sie den Friendly Builder."),
    taskEditorTitle: localize("Create / Edit Task", "Task を作成 / 編集", "Task erstellen / bearbeiten"),
    taskEditorDescription: localize("Configure the prompt, schedule, and runtime behavior in a single compact view.", "prompt、schedule、runtime の動作を 1 つのコンパクトなビューで設定します。", "Konfigurieren Sie prompt, schedule und runtime-Verhalten in einer kompakten Ansicht."),
    taskEditorPromptTitle: localize("Prompt", "Prompt", "Prompt"),
    taskEditorScheduleTitle: localize("Schedule", "Schedule", "Zeitplan"),
    taskEditorRuntimeTitle: localize("Runtime", "Runtime", "Laufzeit"),
    taskEditorOptionsTitle: localize("Options", "オプション", "Optionen"),
    taskEditorActionsTitle: localize("Actions", "アクション", "Aktionen"),
    taskEditorTestPrompt: localize("Test Prompt", "Prompt をテスト", "Prompt testen"),
    jobsRenameFolder: localize("Rename Folder", "フォルダー名を変更", "Ordner umbenennen"),
    jobsDeleteFolder: localize("Delete Folder", "フォルダーを削除", "Ordner löschen"),
    jobsSelectJob: localize("Select a job to edit its workflow.", "workflow を編集する Job を選択してください。", "Wählen Sie einen Job aus, um seinen Workflow zu bearbeiten."),
    jobsName: localize("Job name", "Job 名", "Job-Name"),
    jobsCron: localize("Job schedule", "Job schedule", "Job-Zeitplan"),
    jobsFolder: localize("Folder", "フォルダー", "Ordner"),
    jobsPaused: localize("Inactive", "非アクティブ", "Inaktiv"),
    jobsRunning: localize("Active", "アクティブ", "Aktiv"),
    jobsSave: localize("Save Job", "Job を保存", "Job speichern"),
    jobsDuplicate: localize("Duplicate Job", "Job を複製", "Job duplizieren"),
    jobsDelete: localize("Delete Job", "Job を削除", "Job löschen"),
    jobsPause: localize("Deactivate Job", "Job を非アクティブ化", "Job deaktivieren"),
    jobsResume: localize("Activate Job", "Job を有効化", "Job aktivieren"),
    jobsCompile: localize("Compile To Task", "Compile To Task", "Zu Task kompilieren"),
    jobsHideSidebar: localize("Hide Sidebar", "サイドバーを隠す", "Sidebar ausblenden"),
    jobsShowSidebar: localize("Show Sidebar", "サイドバーを表示", "Sidebar anzeigen"),
    jobsWorkflowTitle: localize("Workflow Studio", "workflow スタジオ", "Workflow-Studio"),
    jobsWorkflowNote: localize("Shape the execution path, inspect pacing, and place human checkpoints before anything runs.", "実行前にフローを整え、進み方を確認し、人の承認ポイントを配置します。", "Gestalten Sie den Ablauf, prüfen Sie das Tempo und setzen Sie menschliche Checkpoints, bevor etwas ausgeführt wird。"),
    jobsWorkflowBadge: localize("Control deck", "コントロールデッキ", "Kontrollzentrum"),
    jobsWorkflowCadence: localize("Cadence", "実行ペース", "Taktung"),
    jobsWorkflowStatus: localize("Status", "ステータス", "Status"),
    jobsWorkflowTaskCount: localize("Task steps", "task ステップ", "Task-Schritte"),
    jobsWorkflowPauseCount: localize("Pause checkpoints", "pause checkpoints", "Pause-Checkpoints"),
    jobsWorkflowTimelineNote: localize("Read the flow left to right. Pause nodes stop the run until you approve the previous result.", "左から右へ flow を確認します。pause node は前の結果を承認するまで実行を止めます。", "Lesen Sie den Ablauf von links nach rechts. Pause-Nodes stoppen den Lauf, bis Sie das vorherige Ergebnis freigeben."),
    jobsCompactTimeline: localize("Workflow timeline", "workflow タイムライン", "Workflow-Zeitleiste"),
    jobsTimelineEmpty: localize("No steps yet", "まだステップはありません", "Noch keine Schritte"),
    jobsToggleStatus: localize("Toggle active status", "アクティブ状態を切り替え", "Aktiv-Status umschalten"),
    jobsSteps: localize("Workflow steps", "workflow ステップ", "Workflow-Schritte"),
    jobsPauseTitle: localize("Pause checkpoints", "Pause checkpoints", "Pause Checkpoints"),
    jobsCreatePause: localize("Create Pause", "Pause を作成", "Pause erstellen"),
    jobsPauseName: localize("Pause title", "Pause タイトル", "Pause-Titel"),
    jobsPauseHelpText: localize("This checkpoint blocks downstream steps until you approve the previous result.", "この checkpoint は、前の結果を承認するまで downstream steps をブロックします。", "Dieser checkpoint blockiert nachgelagerte Schritte, bis Sie das vorherige Ergebnis freigeben."),
    jobsPauseWaiting: localize("Waiting for approval", "承認待ち", "Wartet auf Freigabe"),
    jobsPauseApproved: localize("Approved", "承認済み", "Freigegeben"),
    jobsPauseApprove: localize("Approve", "承認", "Freigeben"),
    jobsPauseReject: localize("Reject and edit previous step", "却下して前のステップを編集", "Ablehnen und vorherigen Schritt bearbeiten"),
    jobsPauseDefaultTitle: localize("Manual review", "手動レビュー", "Manuelle Prüfung"),
    jobsPausePrefix: localize("Pause", "Pause", "Pause"),
    jobsArchivedBadge: localize("Archived", "アーカイブ済み", "Archiviert"),
    jobsPauseEdit: localize("Edit", "編集", "Bearbeiten"),
    jobsPauseDelete: localize("Delete", "削除", "Löschen"),
    jobsArchiveFolderBadge: localize("Bundled jobs", "Bundled jobs", "Gebündelte Jobs"),
    jobsWindowMinutes: localize("Window (minutes)", "ウィンドウ（分）", "Fenster (Minuten)"),
    jobsAddExistingTask: localize("Add Existing Task", "既存の Task を追加", "Vorhandenen Task hinzufügen"),
    jobsAttach: localize("Attach Task", "Task を接続", "Task anhängen"),
    jobsStandaloneTasks: localize("Standalone tasks", "単独の tasks", "Standalone-Tasks"),
    jobsAddNewStep: localize("Add New Step", "新しいステップを追加", "Neuen Schritt hinzufügen"),
    jobsCreateStep: localize("Create Step", "ステップを作成", "Schritt erstellen"),
    jobsStepPrefix: localize("Step", "ステップ", "Schritt"),
    jobsStepName: localize("Step name", "ステップ名", "Schrittname"),
    jobsStepPrompt: localize("Step prompt", "ステップ prompt", "Schritt-Prompt"),
    jobsNoJobs: localize("No jobs in this folder yet.", "このフォルダーにはまだ Jobs がありません。", "In diesem Ordner gibt es noch keine Jobs."),
    jobsNoFolders: localize("No folders yet.", "まだフォルダーはありません。", "Noch keine Ordner."),
    jobsNoStandaloneTasks: localize("No standalone tasks available.", "利用可能な standalone tasks はありません。", "Keine Standalone-Tasks verfügbar."),
    jobsEmptySteps: localize("This job has no steps yet.", "この Job にはまだステップがありません。", "Dieser Job hat noch keine Schritte."),
    jobsDropHint: localize("Drag steps to reorder the timeline.", "ステップをドラッグしてタイムラインを並べ替えます。", "Ziehen Sie Schritte, um die Zeitleiste neu anzuordnen."),
    researchTitle: localize("Benchmark Research", "Benchmark Research", "Benchmark-Research"),
    researchProfilesTitle: localize("Profiles", "プロファイル", "Profile"),
    researchActiveRunTitle: localize("Run details", "実行詳細", "Laufdetails"),
    researchHistoryTitle: localize("Recent runs", "最近の実行", "Letzte Läufe"),
    researchEmptyProfiles: localize("No research profiles yet.", "まだ research profiles はありません。", "Noch keine Research-Profile."),
    researchEmptyRuns: localize("No research runs yet.", "まだ research runs はありません。", "Noch keine Research-Läufe."),
    researchNewProfile: localize("New Profile", "新しい Profile", "Neues Profil"),
    researchLoadAutoAgentExample: localize("Load AutoAgent Example", "AutoAgent の例を読み込む", "AutoAgent-Beispiel laden"),
    researchCreateProfile: localize("Create Profile", "Profile を作成", "Profil erstellen"),
    researchSaveProfile: localize("Save Profile", "Profile を保存", "Profil speichern"),
    researchDuplicateProfile: localize("Duplicate Profile", "Profile を複製", "Profil duplizieren"),
    researchDeleteProfile: localize("Delete Profile", "Profile を削除", "Profil löschen"),
    researchStartRun: localize("Start Run", "実行を開始", "Lauf starten"),
    researchStopRun: localize("Stop Run", "実行を停止", "Lauf stoppen"),
    researchName: localize("Profile name", "Profile 名", "Profilname"),
    researchInstructions: localize("Instructions", "Instructions", "Anweisungen"),
    researchInstructionsPlaceholder: localize("Describe the goal and the kind of focused edits Copilot should attempt.", "目標と、Copilot に試してほしい集中的な編集の種類を説明してください。", "Beschreiben Sie das Ziel und die Art gezielter Änderungen, die Copilot versuchen soll."),
    researchEditablePaths: localize("Editable files", "編集可能ファイル", "Editierbare Dateien"),
    researchEditablePathsPlaceholder: "src/file.ts\nsrc/other.ts",
    researchBenchmarkCommand: localize("Benchmark command", "Benchmark command", "Benchmark-Befehl"),
    researchBenchmarkPlaceholder: "npm test -- --runInBand",
    researchMetricPattern: localize("Metric regex", "Metric regex", "Metric-regex"),
    researchMetricPatternPlaceholder: "score:\\s*([0-9.]+)",
    researchMetricDirection: localize("Metric direction", "Metric の方向", "Metric-Richtung"),
    researchDirectionMaximize: localize("Maximize", "最大化", "Maximieren"),
    researchDirectionMinimize: localize("Minimize", "最小化", "Minimieren"),
    researchMaxIterations: localize("Max iterations", "最大反復回数", "Max. Iterationen"),
    researchMaxMinutes: localize("Max minutes", "最大分数", "Max. Minuten"),
    researchMaxFailures: localize("Max consecutive failures", "最大連続失敗回数", "Max. aufeinanderfolgende Fehler"),
    researchBenchmarkTimeout: localize("Benchmark timeout (seconds)", "Benchmark timeout（秒）", "Benchmark-Timeout (Sekunden)"),
    researchEditWait: localize("Copilot edit settle time (seconds)", "Copilot edit settle time（秒）", "Copilot-Edit-Beruhigungszeit (Sekunden)"),
    researchCurrentBest: localize("Current best", "現在のベスト", "Aktuell bester Wert"),
    researchNoScore: localize("No score yet", "まだスコアなし", "Noch kein Score"),
    researchStatusIdle: localize("Idle", "待機中", "Leerlauf"),
    researchStatusRunning: localize("Running", "実行中", "Läuft"),
    researchStatusStopping: localize("Stopping", "停止中", "Wird gestoppt"),
    researchStatusCompleted: localize("Completed", "完了", "Abgeschlossen"),
    researchStatusFailed: localize("Failed", "失敗", "Fehlgeschlagen"),
    researchStatusStopped: localize("Stopped", "停止済み", "Gestoppt"),
    researchAttempts: localize("Attempts", "試行", "Versuche"),
    researchLastOutcome: localize("Last outcome", "最後の結果", "Letztes Ergebnis"),
    researchStopReason: localize("Stop reason", "停止理由", "Grund für das Stoppen"),
    researchActiveRunEmpty: localize("No research run is active.", "アクティブな research run はありません。", "Kein aktiver Research-Lauf."),
    researchAttemptTimeline: localize("Attempt timeline", "試行タイムライン", "Versuchszeitleiste"),
    researchBaselineLabel: localize("Baseline", "Baseline", "Baseline"),
    researchIterationLabel: localize("Iteration", "Iteration", "Iteration"),
    researchStartedAt: localize("Started", "開始", "Gestartet"),
    researchFinishedAt: localize("Finished", "終了", "Beendet"),
    researchDuration: localize("Duration", "所要時間", "Dauer"),
    researchBaselineScore: localize("Baseline score", "Baseline score", "Baseline-Score"),
    researchBestScore: localize("Best score", "ベストスコア", "Bester Score"),
    researchCompletedIterations: localize("Completed iterations", "完了した反復", "Abgeschlossene Iterationen"),
    researchChangedFiles: localize("Changed files", "変更されたファイル", "Geänderte Dateien"),
    researchViolationFiles: localize("Policy violation files", "ポリシー違反ファイル", "Dateien mit Richtlinienverstößen"),
    researchBenchmarkOutput: localize("Benchmark output", "Benchmark 出力", "Benchmark-Ausgabe"),
    researchExitCode: localize("Exit code", "終了コード", "Exit-Code"),
    researchSnapshot: localize("Snapshot", "Snapshot", "Snapshot"),
    researchMetricPatternShort: localize("Metric", "Metric", "Metric"),
    researchBudgetShort: localize("Budget", "Budget", "Budget"),
    researchEditableCount: localize("Editable files", "編集可能ファイル", "Editierbare Dateien"),
    researchUnsavedNew: localize("New profile", "新しい Profile", "Neues Profil"),
    researchUnsavedChanges: localize("Unsaved changes", "未保存の変更", "Ungespeicherte Änderungen"),
    researchNoRunSelected: localize("Select a recent run to inspect its attempts.", "最近の実行を選んで試行内容を確認してください。", "Wählen Sie einen letzten Lauf aus, um seine Versuche zu prüfen."),
    researchProfileNameRequired: localize("Research profile name is required.", "Research profile 名が必要です。", "Ein Research-Profilname ist erforderlich."),
    researchBenchmarkRequired: localize("Benchmark command is required.", "Benchmark command が必要です。", "Ein Benchmark-Befehl ist erforderlich."),
    researchMetricRequired: localize("Metric regex is required.", "Metric regex が必要です。", "Ein Metric-regex ist erforderlich."),
    researchEditableRequired: localize("Add at least one editable file path.", "少なくとも 1 つの編集可能ファイルパスを追加してください。", "Fügen Sie mindestens einen editierbaren Dateipfad hinzu."),
    researchHelpText: localize("This first implementation runs bounded benchmark iterations against a small allowlisted file set and records keep or revert outcomes in repo-local history.", "この最初の実装では、小さな allowlist のファイルセットに対して制限付き benchmark iterations を実行し、keep または revert の結果をリポジトリローカルの history に記録します。", "Diese erste Implementierung führt begrenzte Benchmark-Iterationen auf einem kleinen allowlisted-Dateisatz aus und protokolliert Keep- oder Revert-Ergebnisse in einer repository-lokalen History."),
    researchAutoAgentExampleName: localize("AutoAgent Harbor Example", "AutoAgent Harbor の例", "AutoAgent-Harbor-Beispiel"),
    researchAutoAgentExampleInstructions: localize("Use this preset inside the autoagent repo to improve the Harbor agent harness score by editing agent.py while refining the experiment directive in program.md. Start with one representative task, keep the editable surface small, and make sure the benchmark command prints a final numeric score or reward line that matches the regex before you run the loop.", "このプリセットは autoagent リポジトリ内で使い、agent.py を編集しながら program.md の実験指示も調整して Harbor エージェントハーネスのスコア改善を狙います。まずは代表的な 1 つのタスクから始め、編集対象を小さく保ち、ループを実行する前に benchmark command が regex に一致する最終的な数値 score または reward 行を出力することを確認してください。", "Verwenden Sie dieses Preset im autoagent-Repository, um den Score des Harbor-Agent-Harness zu verbessern, indem Sie agent.py bearbeiten und zugleich die Versuchsanweisung in program.md verfeinern. Beginnen Sie mit einer repräsentativen einzelnen Aufgabe, halten Sie die editierbare Oberfläche klein und stellen Sie sicher, dass der Benchmark-Befehl vor dem Start der Schleife eine abschließende numerische Score- oder Reward-Zeile ausgibt, die zum Regex passt."),
    labelPromptType: messages.labelPromptType(),
    labelPromptInline: messages.labelPromptInline(),
    labelPromptLocal: messages.labelPromptLocal(),
    labelPromptGlobal: messages.labelPromptGlobal(),
    labelPrompt: messages.labelPrompt(),
    labelSchedule: messages.labelSchedule(),
    labelCronExpression: messages.labelCronExpression(),
    labelPreset: messages.labelPreset(),
    labelCustom: messages.labelCustom(),
    labelAgent: messages.labelAgent(),
    labelModel: messages.labelModel(),
    labelModelNote: messages.labelModelNote(),
    labelScope: messages.labelScope(),
    labelScopeGlobal: messages.labelScopeGlobal(),
    labelScopeWorkspace: messages.labelScopeWorkspace(),
    labelEnabled: messages.labelEnabled(),
    labelDisabled: messages.labelDisabled(),
    labelStatus: messages.labelStatus(),
    labelNextRun: messages.labelNextRun(),
    labelLastRun: messages.labelLastRun(),
    labelNever: messages.labelNever(),
    labelRunFirstInOneMinute: messages.labelRunFirstInOneMinute(),
    labelOneTime: messages.labelOneTime(),
    labelChatSession: messages.labelChatSession(),
    labelChatSessionNew: messages.labelChatSessionNew(),
    labelChatSessionContinue: messages.labelChatSessionContinue(),
    labelChatSessionBadgeNew: messages.labelChatSessionBadgeNew(),
    labelChatSessionBadgeContinue: messages.labelChatSessionBadgeContinue(),
    labelChatSessionRecurringOnly: messages.labelChatSessionRecurringOnly(),
    labelManualSession: messages.labelManualSession(),
    labelManualSessions: messages.labelManualSessions(),
    labelManualSessionNote: messages.labelManualSessionNote(),
    labelAllTasks: messages.labelAllTasks(),
    labelJobTasks: messages.labelJobTasks(),
    labelRecurringTasks: messages.labelRecurringTasks(),
    labelTodoTaskDrafts: messages.labelTodoTaskDrafts(),
    labelOneTimeTasks: messages.labelOneTimeTasks(),
    labelJitterSeconds: messages.labelJitterSeconds(),
    placeholderTaskName: messages.placeholderTaskName(),
    placeholderPrompt: messages.placeholderPrompt(),
    placeholderCron: messages.placeholderCron(),
    invalidCronExpression: messages.invalidCronExpression(),
    taskNameRequired: messages.taskNameRequired(),
    promptRequired: messages.promptRequired(),
    templateRequired: messages.templateRequired(),
    cronExpressionRequired: messages.cronExpressionRequired(),
    actionCreate: messages.actionCreate(),
    actionSave: messages.actionSave(),
    actionNewTask: messages.actionNewTask(),
    actionTestRun: messages.actionTestRun(),
    actionRun: messages.actionRun(),
    actionEdit: messages.actionEdit(),
    actionDelete: messages.actionDelete(),
    actionRefresh: messages.actionRefresh(),
    actionCopyPrompt: messages.actionCopyPrompt(),
    actionDuplicate: messages.actionDuplicate(),
    actionMoveToCurrentWorkspace: messages.actionMoveToCurrentWorkspace(),
    actionEnable: messages.actionEnable(),
    actionDisable: messages.actionDisable(),
    noTasksFound: messages.noTasksFound(),
    labelAdvanced: messages.labelAdvanced(),
    labelFrequency: messages.labelFrequency(),
    labelFrequencyMinute: messages.labelFrequencyMinute(),
    labelFrequencyHourly: messages.labelFrequencyHourly(),
    labelFrequencyDaily: messages.labelFrequencyDaily(),
    labelFrequencyWeekly: messages.labelFrequencyWeekly(),
    labelFrequencyMonthly: messages.labelFrequencyMonthly(),
    labelSelectDays: messages.labelSelectDays(),
    labelSelectTime: messages.labelSelectTime(),
    labelInterval: messages.labelInterval(),
    daySun: messages.daySun(),
    dayMon: messages.dayMon(),
    dayTue: messages.dayTue(),
    dayWed: messages.dayWed(),
    dayThu: messages.dayThu(),
    dayFri: messages.dayFri(),
    daySat: messages.daySat(),
    labelFriendlyBuilder: messages.labelFriendlyBuilder(),
    labelFriendlyGenerate: messages.labelFriendlyGenerate(),
    labelFriendlyPreview: messages.labelFriendlyPreview(),
    labelFriendlyFallback: messages.labelFriendlyFallback(),
    labelFriendlySelect: messages.labelFriendlySelect(),
    labelEveryNMinutes: messages.labelEveryNMinutes(),
    labelHourlyAtMinute: messages.labelHourlyAtMinute(),
    labelDailyAtTime: messages.labelDailyAtTime(),
    labelWeeklyAtTime: messages.labelWeeklyAtTime(),
    labelMonthlyAtTime: messages.labelMonthlyAtTime(),
    labelMinute: messages.labelMinute(),
    labelHour: messages.labelHour(),
    labelDayOfMonth: messages.labelDayOfMonth(),
    labelDayOfWeek: messages.labelDayOfWeek(),
    labelOpenInGuru: messages.labelOpenInGuru(),
    cronPreviewEveryNMinutes: messages.cronPreviewEveryNMinutes(),
    cronPreviewHourlyAtMinute: messages.cronPreviewHourlyAtMinute(),
    cronPreviewDailyAt: messages.cronPreviewDailyAt(),
    cronPreviewWeekdaysAt: messages.cronPreviewWeekdaysAt(),
    cronPreviewWeeklyOnAt: messages.cronPreviewWeeklyOnAt(),
    cronPreviewMonthlyOnAt: messages.cronPreviewMonthlyOnAt(),
    placeholderSelectAgent: messages.webviewSelectAgentPlaceholder(),
    placeholderNoAgents: messages.webviewNoAgentsAvailable(),
    placeholderSelectModel: messages.webviewSelectModelPlaceholder(),
    placeholderNoModels: messages.webviewNoModelsAvailable(),
    placeholderSelectTemplate: messages.webviewSelectTemplatePlaceholder(),
    webviewScriptErrorPrefix: messages.webviewScriptErrorPrefix(),
    webviewUnhandledErrorPrefix: messages.webviewUnhandledErrorPrefix(),
    webviewLinePrefix: messages.webviewLinePrefix(),
    webviewLineSuffix: messages.webviewLineSuffix(),
    webviewUnknown: messages.webviewUnknown(),
    webviewApiUnavailable: messages.webviewApiUnavailable(),
    webviewClientErrorPrefix: messages.webviewClientErrorPrefix(),
    webviewSuccessPrefix: messages.webviewSuccessPrefix(),
    webviewJitterNote: messages.webviewJitterNote(),
    labelThisWorkspaceShort: messages.labelThisWorkspaceShort(),
    labelOtherWorkspaceShort: messages.labelOtherWorkspaceShort(),
    autoShowOnStartupEnabled: messages.autoShowOnStartupEnabled(),
    autoShowOnStartupDisabled: messages.autoShowOnStartupDisabled(),
    autoShowOnStartupToggleEnabled: messages.autoShowOnStartupToggleEnabled(),
    autoShowOnStartupToggleDisabled: messages.autoShowOnStartupToggleDisabled(),
    scheduleHistoryLabel: messages.scheduleHistoryLabel(),
    scheduleHistoryPlaceholder: messages.scheduleHistoryPlaceholder(),
    scheduleHistoryEmpty: messages.scheduleHistoryEmpty(),
    scheduleHistoryNote: messages.scheduleHistoryNote(),
    scheduleHistoryRestoreConfirm: messages.scheduleHistoryRestoreConfirm("{createdAt}"),
    scheduleHistoryRestoreSelectRequired: messages.scheduleHistoryRestoreSelectRequired(),
    actionRestoreBackup: messages.actionRestoreBackup(),
  };
}
